#' Smart Location Database.
#'
#' Smart Location Database by US EPA.
#'
#' @format The main data frame \code{SLD_df} has 220653 rows and 150 variables:
#' \describe{
#'   \item{AC_LAND}{}
#'   \item{AC_TOT}{}
#'   \item{AC_UNPR}{}
#'   \item{AC_WATER}{}
#'   \item{AUTOOWN0}{}
#'   \item{AUTOOWN1}{}
#'   \item{AUTOOWN2P}{}
#'   \item{BGWORKERS}{}
#'   \item{CBSA}{}
#'   \item{CBSA_EMP}{}
#'   \item{CBSA_Name}{}
#'   \item{CBSA_POP}{}
#'   \item{CBSA_WRK}{}
#'   \item{CFIPS}{}
#'   \item{COUNTHU10}{}
#'   \item{CSA}{}
#'   \item{CSA_Name}{}
#'   \item{D1A}{}
#'   \item{D1B}{}
#'   \item{D1C}{}
#'   \item{D1C5_Ent10}{}
#'   \item{D1C5_Ind10}{}
#'   \item{D1C5_Off10}{}
#'   \item{D1C5_Ret10}{}
#'   \item{D1C5_Svc10}{}
#'   \item{D1C8_Ed10}{}
#'   \item{D1C8_Ent10}{}
#'   \item{D1C8_Hlth1}{}
#'   \item{D1C8_Ind10}{}
#'   \item{D1C8_Off10}{}
#'   \item{D1C8_Pub10}{}
#'   \item{D1C8_Ret10}{}
#'   \item{D1C8_Svc10}{}
#'   \item{D1D}{}
#'   \item{D1_flag}{}
#'   \item{D2A_EPHHM}{}
#'   \item{D2A_JPHH}{}
#'   \item{D2A_WRKEMP}{}
#'   \item{D2B_E5MIX}{}
#'   \item{D2B_E5MIXA}{}
#'   \item{D2B_E8MIX}{}
#'   \item{D2B_E8MIXA}{}
#'   \item{D2C_TRIPEQ}{}
#'   \item{D2C_TRPMX1}{}
#'   \item{D2C_TRPMX2}{}
#'   \item{D2C_WREMIX}{}
#'   \item{D2R_JOBPOP}{}
#'   \item{D2R_WRKEMP}{}
#'   \item{D3a}{}
#'   \item{D3aao}{}
#'   \item{D3amm}{}
#'   \item{D3apo}{}
#'   \item{D3b}{}
#'   \item{D3bao}{}
#'   \item{D3bmm3}{}
#'   \item{D3bmm4}{}
#'   \item{D3bpo3}{}
#'   \item{D3bpo4}{}
#'   \item{D4a}{}
#'   \item{D4b025}{}
#'   \item{D4b050}{}
#'   \item{D4c}{}
#'   \item{D4d}{}
#'   \item{D5ae}{}
#'   \item{D5ar}{}
#'   \item{D5be}{}
#'   \item{D5be_Flag}{}
#'   \item{D5br}{}
#'   \item{D5br_Flag}{}
#'   \item{D5ce}{}
#'   \item{D5cei}{}
#'   \item{D5cr}{}
#'   \item{D5cri}{}
#'   \item{D5de}{}
#'   \item{D5dei}{}
#'   \item{D5dr}{}
#'   \item{D5dri}{}
#'   \item{E5_ENT10}{}
#'   \item{E5_IND10}{}
#'   \item{E5_OFF10}{}
#'   \item{E5_RET10}{}
#'   \item{E5_SVC10}{}
#'   \item{E8_ED10}{}
#'   \item{E8_ENT10}{}
#'   \item{E8_HLTH10}{}
#'   \item{E8_IND10}{}
#'   \item{E8_OFF10}{}
#'   \item{E8_PUB10}{}
#'   \item{E8_RET10}{}
#'   \item{E8_SVC10}{}
#'   \item{E_FEDENT10}{}
#'   \item{E_FEDIND10}{}
#'   \item{E_FEDOFF10}{}
#'   \item{E_FEDRET10}{}
#'   \item{E_FEDSVC10}{}
#'   \item{E_FEDT10}{}
#'   \item{E_HIWAGEWK}{}
#'   \item{E_LOWWAGEW}{}
#'   \item{E_MEDWAGEW}{}
#'   \item{EMPTOT}{}
#'   \item{E_PCTLOWWA}{}
#'   \item{GEOID10}{}
#'   \item{HH}{}
#'   \item{LSADC}{}
#'   \item{PCT_AO0}{}
#'   \item{PCT_AO1}{}
#'   \item{PCT_AO2P}{}
#'   \item{P_WRKAGE}{}
#'   \item{R_HIWAGEWK}{}
#'   \item{R_LOWWAGEW}{}
#'   \item{R_MEDWAGEW}{}
#'   \item{R_PCTLOWWA}{}
#'   \item{SFIPS}{}
#'   \item{Shape_Area}{}
#'   \item{Shape_Leng}{}
#'   \item{TOTPOP10}{}
#'   \item{TRAC_LAND}{}
#'   \item{TRACT}{}
#'   \item{TRAC_UNPR}{}
#'   \item{TRAREA}{}
#'   \item{TRE5_ENT10}{}
#'   \item{TRE5_IND10}{}
#'   \item{TRE5_OFF10}{}
#'   \item{TRE5_RET10}{}
#'   \item{TRE5_SVC10}{}
#'   \item{TRE8_ED10}{}
#'   \item{TRE8_ENT10}{}
#'   \item{TRE8_HLTH10}{}
#'   \item{TRE8_IND10}{}
#'   \item{TRE8_OFF10}{}
#'   \item{TRE8_PUB10}{}
#'   \item{TRE8_RET10}{}
#'   \item{TRE8_SVC10}{}
#'   \item{TREMP}{}
#'   \item{TRFIPS}{}
#'   \item{TRHU}{}
#'   \item{TRPOP}{}
#'   \item{TRShape_Area}{}
#'   \item{UACE}{}
#'   \item{UA_NAME}{}
#'   \item{Urban}{}
#'   \item{UZAAC_LAND}{}
#'   \item{UZAACTDEN}{}
#'   \item{UZAAC_UNPR}{}
#'   \item{UZAAREA}{}
#'   \item{UZAEMPDEN}{}
#'   \item{UZAHUDEN}{}
#'   \item{UZAPOP}{}
#'   \item{UZAPOPDEN}{}
#'   \item{UZAShape_Area}{}
#'   }
#'
#'
#' @source \url{https://www.epa.gov/smartgrowth/smart-location-mapping#SLD}
#' @import tidyverse
#' @examples
#' str(SLD_df)
#' head(SLD_df)
#' summary(SLD_df)
#'
"SLD_df"
